apiVersion: arete.arete.io/v1alpha1
kind: BackupRepository
metadata:
  labels:
    app.kubernetes.io/name: arete
    app.kubernetes.io/managed-by: kustomize
  name: backuprepository-sample
spec:
  # TODO(user): Add fields here
