//go:build !ignore_autogenerated

/*
Copyright 2026 Tobias Hofmaenner.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRepository) DeepCopyInto(out *BackupRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRepository.
func (in *BackupRepository) DeepCopy() *BackupRepository {
	if in == nil {
		return nil
	}
	out := new(BackupRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRepositoryList) DeepCopyInto(out *BackupRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRepositoryList.
func (in *BackupRepositoryList) DeepCopy() *BackupRepositoryList {
	if in == nil {
		return nil
	}
	out := new(BackupRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRepositorySpec) DeepCopyInto(out *BackupRepositorySpec) {
	*out = *in
	in.S3.DeepCopyInto(&out.S3)
	out.ProbeInterval = in.ProbeInterval
	out.MetadataValidationInterval = in.MetadataValidationInterval
	if in.SampledRetrievalInterval != nil {
		in, out := &in.SampledRetrievalInterval, &out.SampledRetrievalInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.SampledRetrievalObjects != nil {
		in, out := &in.SampledRetrievalObjects, &out.SampledRetrievalObjects
		*out = new(int32)
		**out = **in
	}
	if in.FullRetrievalInterval != nil {
		in, out := &in.FullRetrievalInterval, &out.FullRetrievalInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.FullRetrievalStorageClass != nil {
		in, out := &in.FullRetrievalStorageClass, &out.FullRetrievalStorageClass
		*out = new(string)
		**out = **in
	}
	if in.FullRetrievalPVCSize != nil {
		in, out := &in.FullRetrievalPVCSize, &out.FullRetrievalPVCSize
		x := (*in).DeepCopy()
		*out = &x
	}
	out.MaxBackupLag = in.MaxBackupLag
	if in.ExpectedSizeBudget != nil {
		in, out := &in.ExpectedSizeBudget, &out.ExpectedSizeBudget
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRepositorySpec.
func (in *BackupRepositorySpec) DeepCopy() *BackupRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(BackupRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRepositoryStatus) DeepCopyInto(out *BackupRepositoryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastProbedAt != nil {
		in, out := &in.LastProbedAt, &out.LastProbedAt
		*out = (*in).DeepCopy()
	}
	if in.ClaimedLatestBackup != nil {
		in, out := &in.ClaimedLatestBackup, &out.ClaimedLatestBackup
		*out = new(LatestBackupStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ClaimedLastSuccessfulBackup != nil {
		in, out := &in.ClaimedLastSuccessfulBackup, &out.ClaimedLastSuccessfulBackup
		*out = (*in).DeepCopy()
	}
	if in.ObservedInventory != nil {
		in, out := &in.ObservedInventory, &out.ObservedInventory
		*out = new(InventoryStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ObservedGrowth != nil {
		in, out := &in.ObservedGrowth, &out.ObservedGrowth
		*out = new(GrowthStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.VerifiedLastValidationAt != nil {
		in, out := &in.VerifiedLastValidationAt, &out.VerifiedLastValidationAt
		*out = (*in).DeepCopy()
	}
	if in.LastFullRetrieval != nil {
		in, out := &in.LastFullRetrieval, &out.LastFullRetrieval
		*out = new(FullRetrievalStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRepositoryStatus.
func (in *BackupRepositoryStatus) DeepCopy() *BackupRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(BackupRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionalConfig) DeepCopyInto(out *ConditionalConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionalConfig.
func (in *ConditionalConfig) DeepCopy() *ConditionalConfig {
	if in == nil {
		return nil
	}
	out := new(ConditionalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConditionalConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionalConfigList) DeepCopyInto(out *ConditionalConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConditionalConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionalConfigList.
func (in *ConditionalConfigList) DeepCopy() *ConditionalConfigList {
	if in == nil {
		return nil
	}
	out := new(ConditionalConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConditionalConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionalConfigSpec) DeepCopyInto(out *ConditionalConfigSpec) {
	*out = *in
	if in.Foo != nil {
		in, out := &in.Foo, &out.Foo
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionalConfigSpec.
func (in *ConditionalConfigSpec) DeepCopy() *ConditionalConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ConditionalConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionalConfigStatus) DeepCopyInto(out *ConditionalConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionalConfigStatus.
func (in *ConditionalConfigStatus) DeepCopy() *ConditionalConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ConditionalConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FullRetrievalStatus) DeepCopyInto(out *FullRetrievalStatus) {
	*out = *in
	in.CompletedAt.DeepCopyInto(&out.CompletedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FullRetrievalStatus.
func (in *FullRetrievalStatus) DeepCopy() *FullRetrievalStatus {
	if in == nil {
		return nil
	}
	out := new(FullRetrievalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrowthStatus) DeepCopyInto(out *GrowthStatus) {
	*out = *in
	out.Window = in.Window
	out.Bytes = in.Bytes.DeepCopy()
	in.SampledAt.DeepCopyInto(&out.SampledAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrowthStatus.
func (in *GrowthStatus) DeepCopy() *GrowthStatus {
	if in == nil {
		return nil
	}
	out := new(GrowthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InventoryStatus) DeepCopyInto(out *InventoryStatus) {
	*out = *in
	out.TotalBytes = in.TotalBytes.DeepCopy()
	if in.OldestObject != nil {
		in, out := &in.OldestObject, &out.OldestObject
		*out = (*in).DeepCopy()
	}
	if in.NewestObject != nil {
		in, out := &in.NewestObject, &out.NewestObject
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InventoryStatus.
func (in *InventoryStatus) DeepCopy() *InventoryStatus {
	if in == nil {
		return nil
	}
	out := new(InventoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LatestBackupStatus) DeepCopyInto(out *LatestBackupStatus) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	out.SizeBytes = in.SizeBytes.DeepCopy()
	if in.UncompressedSizeBytes != nil {
		in, out := &in.UncompressedSizeBytes, &out.UncompressedSizeBytes
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LatestBackupStatus.
func (in *LatestBackupStatus) DeepCopy() *LatestBackupStatus {
	if in == nil {
		return nil
	}
	out := new(LatestBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Source) DeepCopyInto(out *S3Source) {
	*out = *in
	in.CredentialsSecret.DeepCopyInto(&out.CredentialsSecret)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Source.
func (in *S3Source) DeepCopy() *S3Source {
	if in == nil {
		return nil
	}
	out := new(S3Source)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
	if in.KeyMapping != nil {
		in, out := &in.KeyMapping, &out.KeyMapping
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}
